class Exception6
{
public static void main(String args[])
{
int i=50;
int j=0;
int data;
try
{
data=i/j;
}
catch(Exception e)
{
int datta2=50/0;
}
System.out.println("rest");
}}