class Exception1
{
public static void main(String args[])
{
try
{
int data=100/0;
int p=30;
}
catch(ArithmeticException e)
{
System.out.println(e);
}
System.out.println("rest of code");
}
}










